### ISSUE TITLE
Monte Carlo error

### ISSUE THREAD

**Issue by snirgaz** [JuliaDiffEq/StochasticDiffEq.jl#50]
While trying to set up a Monte Carlo calculation based on the examples in the documentation, I encountered the following error:

`julia> using StochasticDiffEq

julia> u=0.0
0.0

julia> f(t,u) = 0.0
f (generic function with 1 method)

julia> g(t,u) = 1.0
g (generic function with 1 method)

julia> prob = SDEProblem(f,g,u,(0.0,1.0))
DiffEqBase.SDEProblem with uType Float64 and tType Float64. In-place: false
timespan: (0.0, 1.0)
u0: 0.0

julia> monte_prob = MonteCarloProblem(prob)
DiffEqBase.MonteCarloProblem with problem DiffEqBase.SDEProblem

julia> sol = solve(monte_prob,num_monte=1000,paralle_type=:threads)
ERROR: MethodError: no method matching solve(::DiffEqBase.MonteCarloProblem{DiffEqBase.SDEProblem{Float64,Float64,false,Void,#f,#g,Void,UniformScaling{Int64},Void},DiffEqBase.##205#211,DiffEqBase.##204#210,DiffEqBase.##206#212,Array{Any,1}}; num_monte=1000, paralle_type=:threads)
Closest candidates are:
  solve(::DiffEqBase.AbstractODEProblem{uType,tType,isinplace}, ::DiffEqBase.InternalEuler.FwdEulerAlg; dt, tstops, kwargs...) where {uType, tType, isinplace} at /Users/snirgaz/.julia/v0.6/DiffEqBase/src/internal_euler.jl:21
  solve(::DiffEqBase.AbstractODEProblem{uType,tType,isinplace}, ::DiffEqBase.InternalEuler.BwdEulerAlg; dt, tstops, tol, maxiter, kwargs...) where {uType, tType, isinplace} at /Users/snirgaz/.julia/v0.6/DiffEqBase/src/internal_euler.jl:51
  solve(::DiffEqBase.AbstractNoiseProblem, ::Void, ::Any...; dt, kwargs...) at /Users/snirgaz/.julia/v0.6/DiffEqNoiseProcess/src/solve.jl:1
  ...

`
I must be doing something wrong... but it seems like "solve" does not take an MC type.

Any suggestions?

**Comment by ChrisRackauckas** [comment]
The working code is:

```julia
using StochasticDiffEq, DiffEqMonteCarlo
u=0.0
f(t,u) = 0.0
g(t,u) = 1.0
prob = SDEProblem(f,g,u,(0.0,1.0))
monte_prob = MonteCarloProblem(prob)
sol = solve(monte_prob,SRA1(),num_monte=1000,parallel_type=:threads)
```

A few things to explain:

1) I highly recommend starting with DifferentialEquations.jl, and then using the tips [from the Low Dependency](http://docs.juliadiffeq.org/stable/features/low_dep.html) page if you need to narrow down the dependencies (or just ask, they are usually not many).
2) What was missing was DiffEqMonteCarlo.jl which has the solver routines for the MonteCarloProblems.
3) You wrote `paralle_type` instead of `parallel_type` which also would cause a method mismatch (though Julia would error there, telling you that a keyword arg was incorrect).
4) When not using DifferentialEquations.jl, you need to specify an algorithm. 

The documentation for "going straight to the packages" beyond the simplest case of the ODE solvers could probably be improved so please feel free to give suggestions. Hope this helps!

**Comment by snirgaz** [comment]
Thanks!
BTW - amazing library!
